controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
api_generate_pdf:
    path: /api/generate-pdf
    controller: App\Controller\ApiPdfController::generatePdf
    methods: POST
